// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

  const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIe2Uh5_OPITgZu-qinPxWKHXYinnPUl4',
    appId: '1:96755432259:android:1229aec3cc2b4aecd9cdf6',
    messagingSenderId: '96755432259',
    projectId: 'mad-project-38adf',
    storageBucket: 'mad-project-38adf.firebasestorage.app',
  );

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform => android;
}